### ISSUE TITLE
backspace not working

### ISSUE THREAD

**Issue by ayoubelouardi** [Sahil-B07/Typing-Test#1]
the program is ending with this error : 
**Enter your name: dsaf
Press enter to continue.**
_Traceback (most recent call last):
  File "/home/ayoub/Typing-Test/main.py", line 88, in <module>
    wrapper(main)
  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayoub/Typing-Test/main.py", line 75, in main
    wpm_test(stdscr)
  File "/home/ayoub/Typing-Test/main.py", line 54, in wpm_test
    if ord(key) == 27:
       ^^^^^^^^
TypeError: ord() expected a character, but string of length 13 found_

when i enter a backspace key

**Comment by Sahil-B07** [comment]
Thank you for reporting this issue, @ayoubelouardi
I'll try to resolve it
